### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by LukeSheard** [amannn/graphql-filter-fragment#2]
Thanks for doing this, I was looking for a replacement for this exact function and was about to fork it into a package myself. 

If there's anyway I can help maintain this in future let me know.

**Comment by amannn** [comment]
Hey @LukeSheard, thanks for leaving a note here! 🙂 

Sure, I've just added you as a collaborator. I think currently the package should be up-to-date, but feel free to propose changes in the repo if you find a need!
